### ISSUE TITLE
World size can only go up to 30_918

### ISSUE THREAD

**Issue by Tim2othy** [Tim2othy/spacegame#13]
![image](https://github.com/user-attachments/assets/55842b6b-8010-45e5-b29c-3394f5a84eae)

**Comment by lumi-a** [comment]
I successfully tested a universe of size `(100_000, 100_00)`. As an aside, if we're going to have huge universes, the gridline-draws will:
- Drain a lot of performance on the minimap, because the minimap draws *all* the gridlines. This can be solved by, well, not drawing the gridlines on the minimap. Perhaps we should give the minimap an outline in this case, though, to visually distinguish it from the rest of the screen.
- Drain a lot of performance in general, because the gridline-draw-code looks like this:
    ```py
        for x in range(0, int(width + 1), gridline_spacing):
            camera.draw_hairline(grid_color, Vector2(x, 0), Vector2(x, height))
        for y in range(0, int(height + 1), gridline_spacing):
            camera.draw_hairline(grid_color, Vector2(0, y), Vector2(width, y))
        ```
        i.e., it *attempts* to draw all the gridlines (but, in `camera.draw_hairline`, only visible gridlines are drawn). The loops would have a lot of iterations per frame if the universe became larger, but -- using maths -- we can actually restrict the loop-range to a very narrow interval. I don't want to calculate those ranges right now.
